### ISSUE TITLE
Remove all non-necessary attributes from `TaskImport` (and `TaskExport`?)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-common#6]
**This is to be discussed.**

Out of TaskImport fields, we only use source+name (and maybe in the future we will only use source), but we still include all attributes.

**Comment by jluethi** [comment]
Hmm, actually a good thing to briefly discuss.

My main feedback on the import/export workflows is that it can be 
1) a bit confusing to see both the task defaults and the newly provided args (it's correct, but maybe not complexity we want to expose to the users) 
and more importantly 

2) It can actually be misleading. If we e.g. don't load the `default_args` (why would we when we register the tasks ourselves on the server), a user may change default args expecting this to take effect when they import a workflow. Alternatively, a user may provide a new command with a custom python environment path assuming that this would register this new task with a new command.
This is not the way these things should be done, so I think we shouldn't expose this information here.

----

I can see 2 counter-arguments to removing this information, but I think they weigh less:
1) it may be convenient for debugging to see the full information in the (not that important)
2) It documents what the default_args were when the user ran the task.

On counter-argument 2: I think that can be somewhat important to document. It shouldn't change reproducibility, because a given version of a task will not change its default arguments (unless a rogue admin is at work). But it can still be useful to have those default arguments documented.

----

Overall, I think the additional task attributes (maybe except for the name even if it is not used anymore at some point) should be removed.

**Comment by tcompa** [comment]
Closed as of b5b5b9c65f0ed642b0443c4380ff8fbf66cfe015.
By now we only left name and source as TaskImport and TaskExport attributes, but see also #7
